$enc = [System.Text.Encoding]::UTF8
$lines = [System.IO.File]::ReadAllLines('index.html', $enc)

$newBlock = @(
  '  <!-- ══════════════ SERVICES ══════════════ -->',
  '  <section id="services" class="section">',
  '    <div class="container">',
  '      <div class="services-header fade-up">',
  '        <div>',
  '          <span class="section-label">Lo que ofrecemos</span>',
  '          <h2 class="section-title">Servicios <span class="highlight">profesionales</span></h2>',
  '          <p class="section-subtitle">Soluciones a&#233;reas a medida para cada proyecto, con equipos de &#250;ltima generaci&#243;n y total cobertura de seguro.</p>',
  '        </div>',
  '        <a href="#contact" class="btn btn-outline services-header-cta">Solicitar presupuesto</a>',
  '      </div>',
  '      <div class="services-featured fade-up">',
  '        <div class="svc-card svc-card--featured">',
  '          <div class="svc-card-num">01</div>',
  '          <div class="svc-card-icon"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M3 9.5L12 3l9 6.5V20a1 1 0 01-1 1H4a1 1 0 01-1-1V9.5z"/><path d="M9 21V12h6v9"/></svg></div>',
  '          <span class="svc-card-tag">M&#225;s solicitado</span>',
  '          <h3 class="svc-card-title">Fotograf&#237;a Inmobiliaria</h3>',
  '          <p class="svc-card-desc">Im&#225;genes a&#233;reas que destacan propiedades y urbanizaciones, aumentando su atractivo y valor de venta en portales inmobiliarios.</p>',
  '          <ul class="svc-card-features">',
  '            <li><span class="svc-check">&#10003;</span> Fotos 4K ultra definici&#243;n</li>',
  '            <li><span class="svc-check">&#10003;</span> V&#237;deo cinematogr&#225;fico</li>',
  '            <li><span class="svc-check">&#10003;</span> Entrega en 48 h</li>',
  '          </ul>',
  '          <a href="#contact" class="svc-card-link">Solicitar presupuesto <span>&#8594;</span></a>',
  '        </div>',
  '        <div class="svc-card svc-card--featured">',
  '          <div class="svc-card-num">02</div>',
  '          <div class="svc-card-icon"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><rect x="2" y="7" width="15" height="10" rx="2"/><path d="M17 9.5l5-2.5v10l-5-2.5V9.5z"/></svg></div>',
  '          <span class="svc-card-tag">Cinematogr&#225;fico</span>',
  '          <h3 class="svc-card-title">Producci&#243;n Audiovisual</h3>',
  '          <p class="svc-card-desc">V&#237;deos a&#233;reos de cine para publicidad, series, cortometrajes y contenido de marca. Planos imposibles desde el aire.</p>',
  '          <ul class="svc-card-features">',
  '            <li><span class="svc-check">&#10003;</span> Grabaci&#243;n RAW 4K/6K</li>',
  '            <li><span class="svc-check">&#10003;</span> Edici&#243;n profesional</li>',
  '            <li><span class="svc-check">&#10003;</span> M&#250;sica y color grading</li>',
  '          </ul>',
  '          <a href="#contact" class="svc-card-link">Solicitar presupuesto <span>&#8594;</span></a>',
  '        </div>',
  '      </div>',
  '      <div class="services-grid-4 fade-up">',
  '        <div class="svc-card svc-card--small">',
  '          <div class="svc-card-num">03</div>',
  '          <div class="svc-card-icon svc-card-icon--sm"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z"/></svg></div>',
  '          <h3 class="svc-card-title">Eventos &amp; Bodas</h3>',
  '          <p class="svc-card-desc">Captura los momentos &#250;nicos de tu celebraci&#243;n desde perspectivas irrepetibles e impactantes.</p>',
  '          <a href="#contact" class="svc-card-link">M&#225;s info <span>&#8594;</span></a>',
  '        </div>',
  '        <div class="svc-card svc-card--small">',
  '          <div class="svc-card-num">04</div>',
  '          <div class="svc-card-icon svc-card-icon--sm"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><rect x="2" y="3" width="20" height="14" rx="2"/><path d="M8 21h8M12 17v4"/><path d="M7 8h2v5H7zm4-2h2v7h-2zm4 3h2v4h-2z"/></svg></div>',
  '          <h3 class="svc-card-title">Inspecci&#243;n Industrial</h3>',
  '          <p class="svc-card-desc">Inspecci&#243;n t&#233;cnica de infraestructuras, torres, tejados y plantas industriales con total seguridad.</p>',
  '          <a href="#contact" class="svc-card-link">M&#225;s info <span>&#8594;</span></a>',
  '        </div>',
  '        <div class="svc-card svc-card--small">',
  '          <div class="svc-card-num">05</div>',
  '          <div class="svc-card-icon svc-card-icon--sm"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M3 20l5-10 4 6 3-4 6 8H3z"/><circle cx="17" cy="5" r="2"/></svg></div>',
  '          <h3 class="svc-card-title">Cartograf&#237;a &amp; Topograf&#237;a</h3>',
  '          <p class="svc-card-desc">Levantamientos topogr&#225;ficos, modelos 3D y ortofotograf&#237;as de alta precisi&#243;n para ingenier&#237;a.</p>',
  '          <a href="#contact" class="svc-card-link">M&#225;s info <span>&#8594;</span></a>',
  '        </div>',
  '        <div class="svc-card svc-card--small">',
  '          <div class="svc-card-num">06</div>',
  '          <div class="svc-card-icon svc-card-icon--sm"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M14 14.76V3.5a2.5 2.5 0 00-5 0v11.26a4.5 4.5 0 105 0z"/></svg></div>',
  '          <h3 class="svc-card-title">An&#225;lisis &amp; Termograf&#237;a</h3>',
  '          <p class="svc-card-desc">Detecci&#243;n de p&#233;rdidas t&#233;rmicas y diagn&#243;stico de cubiertas solares con c&#225;mara t&#233;rmica.</p>',
  '          <a href="#contact" class="svc-card-link">M&#225;s info <span>&#8594;</span></a>',
  '        </div>',
  '      </div>',
  '    </div>',
  '  </section>'
)

$result = [System.Collections.Generic.List[string]]::new()
for ($i = 0; $i -lt 121; $i++) { $result.Add($lines[$i]) }
foreach ($line in $newBlock) { $result.Add($line) }
for ($i = 177; $i -lt $lines.Count; $i++) { $result.Add($lines[$i]) }

[System.IO.File]::WriteAllLines('index.html', $result, $enc)
Write-Host ('Done. New line count: ' + $result.Count)
